{% set version = "2.2.5" %}
# Obtain from ZLIB_VERSION in zlib.h.in; https://github.com/zlib-ng/zlib-ng/blob/VERSION/zlib.h.in#L61
{% set zlib_api = "1.3.1" %}
{% set number = 1 %}

package:
  name: zlib-ng
  version: {{ version }}

source:
  url: https://codeload.github.com/zlib-ng/zlib-ng/tar.gz/refs/tags/{{ version }}
  sha256: 5b3b022489f3ced82384f06db1e13ba148cbce38c7941e424d6cb414416acd18
  fn: zlib-ng.tar.gz

build:
  number: {{ number }}
  script_env:
    - ZLIB_COMPAT=0  # [compat == "no"]
    - ZLIB_COMPAT=1  # [compat == "yes"]
  run_exports:
    # Just guessing since the library is so new
    # but they seem to want to be backward compatible
    # https://abi-laboratory.pro/index.php?view=timeline&l=zlib-ng
    - {{ pin_subpackage('zlib-ng', max_pin='x.x') }} # [compat == "no"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:

outputs:
  # zlib-ng gets built when compat is NOT enabled; versioned with the regular zlib-ng release
  - name: zlib-ng
    build:
      skip: true  # [compat == "yes"]
  # zlib and libzlib get built when compat is enabled; they are versioned after the zlib API
  - name: libzlib
    version: {{ zlib_api }}
    build:
      skip: true  # [compat == "no"]
      string: h{{ PKG_HASH }}_ng_{{ version.replace(".", "") }}_{{ number }}  # [compat == "yes"]
      run_exports:
        # This is for compat mode, just libzlib, with major pinning
        - {{ pin_subpackage('libzlib', max_pin='x') }}  # [compat == "yes"]
      track_features:  # [compat == "yes"]
        - zlib-ng-compat  # [compat == "yes"]
    files:
      include:
        - lib/libz.so.*          # [linux]
        - lib/libz.*.dylib       # [osx]
        - Library/bin/zlib.dll   # [win]
        - zlib.dll               # [win]
        - zlib1.dll              # [win]
    test:
      commands:
        - test ! -e $PREFIX/include/zlib.h                          # [unix]
        - test ! -e $PREFIX/lib/libz.a                              # [unix]
        - test ! -e $PREFIX/lib/libz${SHLIB_EXT}                    # [unix]
        - if not exist %LIBRARY_BIN%\zlib.dll exit 1                # [win]
        - if not exist %PREFIX%\zlib.dll exit 1                     # [win]
        - if not exist %LIBRARY_BIN%\zlib1.dll exit 1               # [win]
  - name: zlib
    version: {{ zlib_api }}
    build:
      skip: true  # [compat == "no"]
      number: {{ number }}
      string: h{{ PKG_HASH }}_ng_{{ version.replace(".", "") }}_{{ number }}
      run_exports:
        - {{ pin_subpackage('zlib', max_pin='x') }}
      track_features:
        - zlib-ng-compat
    files:
      include:
        - "**/*"
      exclude:
        - lib/libz.so.*          # [linux]
        - lib/libz.*.dylib       # [osx]
        - Library/bin/zlib.dll   # [win]
        - zlib.dll               # [win]
        - zlib1.dll              # [win]
    requirements:
      run:
        - {{ pin_subpackage("libzlib", exact=True) }}
    test:
      commands:
        - test -e $PREFIX/include/zlib.h                            # [unix]
        - test -e $PREFIX/include/zconf.h                           # [unix]
        - test -e $PREFIX/lib/libz.a                                # [unix]
        - test -e $PREFIX/lib/libz${SHLIB_EXT}                      # [unix]
        - test -e $PREFIX/lib/pkgconfig/zlib.pc                     # [unix]
        - if not exist %LIBRARY_INC%\zlib.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\zconf.h exit 1                 # [win]
        - if not exist %LIBRARY_LIB%\zlib.lib exit 1                # [win]
        - if not exist %LIBRARY_LIB%\zlibstatic.lib exit 1          # [win]
        - if not exist %LIBRARY_LIB%\pkgconfig\zlib.pc exit 1       # [win]

test:
  commands:
{%- if compat == "no" %}
    - test -e $PREFIX/include/zlib-ng.h                         # [unix]
    - test -e $PREFIX/include/zconf-ng.h                        # [unix]
    - test -e $PREFIX/lib/libz-ng${SHLIB_EXT}                   # [unix]
    - test -e $PREFIX/lib/pkgconfig/zlib-ng.pc                  # [unix]
    - if not exist %LIBRARY_INC%\zlib-ng.h exit 1               # [win]
    - if not exist %LIBRARY_INC%\zconf-ng.h exit 1              # [win]
    - if not exist %LIBRARY_BIN%\zlib-ng2.dll exit 1            # [win]
    - if not exist %LIBRARY_LIB%\zlib-ng.lib exit 1             # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\zlib-ng.pc exit 1    # [win]
{%- endif %}

about:
  home: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems

extra:
  feedstock-name: zlib-ng
  recipe-maintainers:
    - hmaarrfk
